### ISSUE TITLE
Sonarr API and CouchPotato API NPM modules

### ISSUE THREAD

**Issue by onedr0p** [calvinbui/Material-Usenet-Dashboard#1]
Hi, I am going to check out your project soon. I just wanted to say that I created 2 full featured NPM modules for accessing the sonarr and couchpotato API. From what I see you can easily add them in your project.

https://github.com/onedr0p/sonarr-api
https://github.com/onedr0p/couchpotato-api

I might fork this sometime and play with it a bit, are you open to pull requests for additional services?

Cheers!

**Comment by calvinbui** [comment]
i'll definitely be interested to take a look lol
where were you a few weeks ago when I had to do this haha.

This is really a personal project, and its not perfect but I'll definitely be open to trying it out later.

**Comment by calvinbui** [comment]
Thanks I've implemented it!
